### ISSUE TITLE
Second display not working in Release APK

### ISSUE THREAD

**Issue by ziakhan110** [VNAPNIC/presentation-displays#7]
**Describe the bug**
When we make release APK , second display does not work.

**Comment by VNAPNIC** [comment]
u run "flutter build apk --release" right?

**Comment by ziakhan110** [comment]
Yes i did that, 
When app is running i get this,

`Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@4748c80) but could not find and invoke the GeneratedPluginRegistrant.
`

**Comment by ziakhan110** [comment]
the problem might be related to proguard shrinking

**Comment by VNAPNIC** [comment]
i don't use proguard shrinking in the project.
u can add to manifest

<meta-data
    android:name="flutterEmbedding"
    android:value="2" />

**Comment by MarcoGolin** [comment]
on debug work normaly, same problem here when run "Flutter run --release" 

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(showPresentation, Value null at displayId of type org.json.JSONObject$1 cannot be 
converted to int, null, null)
E/flutter ( 6899): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter ( 6899): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter ( 6899): <asynchronous suspension>

**Comment by VNAPNIC** [comment]
@MarcoGolin What device are you using?
I think maybe both devices are not connected yet

**Comment by MarcoGolin** [comment]
> @MarcoGolin What device are you using?
> I think maybe both devices are not connected yet

is the Sunmi D2-mini

**Comment by VNAPNIC** [comment]
Sunmi D2-mini i think u should use [flutter_nearby_connections](https://github.com/VNAPNIC/flutter_nearby_connections) for it
We're use [flutter_nearby_connections](https://github.com/VNAPNIC/flutter_nearby_connections) for D2-mini in the my project

**Comment by ziakhan110** [comment]
> i don't use proguard shrinking in the project.
> u can add to manifest
> 
> ```
> <meta-data
>     android:name="flutterEmbedding"
>     android:value="2" />
> ```

my project is already using V2

**Comment by vagers2000** [comment]
Same error to me, release apk is not working and at same place debug one is working.

**Comment by mjafartp** [comment]
Same issue, 
Not working on the release version.

**Comment by EbramTawfik** [comment]
Worked for me by adding a progaurd rule

`-keep class com.namit.** { *; }`

**Comment by azhura14** [comment]
i was use two condition but nothing change

**Comment by ziakhan110** [comment]
https://developer.android.com/reference/android/support/annotation/Keep
Use this to ignore the DisplayJson.kt from obfuscating.

**Comment by ziakhan110** [comment]
Another solution will be to use GSON field name annotations on the DisplayJson.kt fields, this way if the variable name changes the annotated name will remain , and it will work fine.

**Comment by johnfriend88** [comment]
i have added the -keep class com.namit.** { *; } in proguard . but when i release the apk, the  get display shows "null null"

but works with debug mode.





Release mode error:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
                                                                                                    #0      _DisplayManagerScreenState._getDisplays.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:hi/test_project.dart:232)
                                                                                                    #1      List.forEach (dart:core-patch/growable_array.dart:416)
                                                                                                    #2      _DisplayManagerScreenState._getDisplays.<anonymous closure>.<anonymous closure> (package:hi/test_project.dart:231)
                                                                                                    #3      State.setState (package:flutter/src/widgets/framework.dart:1203)
                                                                                                    #4      _DisplayManagerScreenState._getDisplays.<anonymous closure> (package:hi/test_project.dart:226)
                                                                                                    <asynchronous suspension>




Even  when i open example app in release mode, it will show null, null..


I am new to this. could you please help me on this?

**Comment by hrueger** [comment]
It seems like with the latest flutter, that problem also exists in the example app... Just clone the repo, run `flutter pub get`, `cd example`, `flutter build apk --release` and install the apk. `Get Displays` returns `null, null`, `null, null`...

**Comment by patelnirav48** [comment]
@VNAPNIC Could you please help here. When we test using release apk its not working

**Comment by hrueger** [comment]
@patelnirav48 I'm using @arbyazra123's fork successfully (https://github.com/VNAPNIC/presentation-displays/issues/7#issuecomment-906461804)

**Comment by patelnirav48** [comment]
@hrueger I'm using iMin device (connected through HDMI) will it work on that too?

**Comment by hrueger** [comment]
I have no idea - try it and report your findings ;-)

**Comment by patelnirav48** [comment]
@hrueger Tested, and it works. Thanks a lot.

**Comment by dan8551** [comment]
displays_manager.dart line 68-70:
`displays.add(kReleaseMode
          ? displayReleaseFromJson(map as Map<String, dynamic>)
          : displayFromJson(map as Map<String, dynamic>));`

What is the reason for this code? It changes the list keys, breaking the code in release

**Comment by ziakhan110** [comment]
This code is not needed. The author used obfuscated keys for parsing json, but those keys change on each compilation.
The actual soltion is to add this file to prguard rules file to not be obfuscated in release.

Check it here
https://github.com/VNAPNIC/presentation-displays/pull/42

**Comment by ziakhan110** [comment]
Here is prguard rules, this should be added to the readme.md of this library so people know its needed in release apk.

`-keep class com.namit.** { *; }`

**Comment by ziakhan110** [comment]
Here is prguard rules, this should be added to the readme.md of this library so people know its needed in release apk.

`-keep class com.namit.** { *; }`

**Comment by khamenkhai** [comment]
When i release the apk file, the secondary display didn't work.Why?? Please tell me

**Comment by khamenkhai** [comment]
Hello guys, please help me when I release the apk the second display didn't work.Only worked in the debug apk.why is that??

**Comment by patelnirav48** [comment]
> I'm using @arbyazra123's fork successfully ([#7 (comment)](https://github.com/VNAPNIC/presentation-displays/issues/7#issuecomment-906461804))

Check @arbyazra123's fork (https://github.com/VNAPNIC/presentation-displays/issues/7#issuecomment-906461804)
It worked for me.

**Comment by ejjat0909** [comment]
> -keep class com.namit.** { *; }

not working

**Comment by ejjat0909** [comment]
> its because flutter release mode using obfuscating code on it, and DisplayJson.kt in native code will be obfuscated. But I fixed this issue by using klutzy way haha, try this https://github.com/arbyazra123/presentation-displays, I changed the parameter in native android to a = displayId, b = flags, c = rotation, d = displayName, because the compiler obfuscate the fields of DisplayJson.kt, and I tried to generalize it.
> 
> Or you may use the way above me to avoid obfuscating code by using -keep class com.namit.** { *; }

I have tried to run your project, its not working
